### ISSUE TITLE
classpathの設定

### ISSUE THREAD

**Issue by kozo2** [anekos/ironmaiden-clj#1]
がわからなかったのでissueします

https://gist.github.com/kozo2/2b3cdd1206a187853cab953973b0c4a0

**Comment by anekos** [comment]
`feature/native` ブランチじゃないと駄目だと思います。
あと、こいつはまだ全然動く状態ではなかったりします…。

**Comment by anekos** [comment]
iron-maiden-cl のほうで大体どんな機能が必要かわかったので、Lisp 系じゃない言語でやってしまおうかとも思っていたり…。
ちょっとこいつは勿体ないかもですが。

**Comment by kozo2** [comment]
なるほど
